
- name: "Change prompt color"
  lineinfile:
    path: /home/lukasz/.bashrc
    line: export PS1="\[$(tput setaf 3)$(tput bold)\][\u@\h \W]$ \[$(tput sgr0)\]"
    state: present

- name: "add vim alias"
  lineinfile:
    path: /home/lukasz/.bashrc
    line: alias vim=nvim
    state: present


- name: "debug"
  debug: 
    msg: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: "Ensure nvim directory exists"
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
  
- name: "Update init.vim"
  template:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: "Ensure nvim autoload directory exists"
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory



