- name: "debug"
  debug: 
    msg: "{{ ansible_env.HOME }}/"

- name: "Ensure required directories exist"
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0700
  loop:
    - "{{ nvim_dir }}"
    - "{{ nvim_dir }}/autoload"
    - "{{ nvim_dir }}/plugged"
    - "{{ nvim_dir }}/lua"
    - "{{ gnupg_dir }}"
      

- name: "Change prompt color"
  lineinfile:
    path: /home/lukasz/.bashrc
    line: export PS1="\[$(tput setaf 3)$(tput bold)\][\u@\h \W]$ \[$(tput sgr0)\]"
    state: present

- name: "Add lines to .bashrc"
  blockinfile:
    path: /home/lukasz/.bashrc
    block: |
      export PS1="\[$(tput setaf 3)$(tput bold)\][\u@\h \W]$ \[$(tput sgr0)\]"
      
      
      alias vim=nvim
      alias v=nvim
      alias ytaudio="yt-dlp -x -f bestaudio --audio-format best"

- name: "copy files from template"
  template:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    mode: 0600
  loop:   
    - { src: "init.vim", dest: "{{ nvim_dir }}/init.vim" }


- name: Ensure download required files 
  get_url:
    dest: "{{ item.dest }}"
    url: "{{ item.url }}"
  loop: 
    - { url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim,  dest: "{{ nvim_dir }}/autoload/plug.vim" }

