- name: "Change prompt color"
  lineinfile:
    path: /home/lukasz/.bashrc
    line: export PS1="\[$(tput setaf 3)$(tput bold)\][\u@\h \W]$ \[$(tput sgr0)\]"
    state: present


- name: Fedora rpm fusion
  become: yes
  shell: "dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

- name: Install dnf packages
  become: yes
  dnf:
    state: latest
    name: 
      - '@Development Tools'
      - '@Development Libraries'
      - make
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
      - python3-pip
      - dnf-plugins-core
      - gnome-tweaks
      - mosh
      - tmux
      - mpv
      - vim
      - neovim
      - nmap
      - appeditor
      - nextcloud-client
      - gstreamer1-devel
      - gstreamer1-plugins-base-tools
      - gstreamer1-doc
      - gstreamer1-plugins-base-devel 
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-devel
      - gstreamer1-plugins-bad-free-extras
      - qbittorrent
      - tilix
      - htop
      - foliate
      - bridge-utils
      - libvirt
      - virt-install
      - qemu-kvm
      - libvirt-devel
      - virt-top
      - libguestfs-tools
      - virt-manager
      - openssh-server
      - ansible
      - yubikey-manager
      - nodejs
      - autofs
      - acpid
      - dkms
      - ncurses-compat-libs
      - alacritty
      - youtube-dl
      - ffmpeg
      - inxi
      - nemo
      - nemo-extensions
      - nemo-fileroller
      - kleopatra


        #- name: Add the flathub flatpak remote to the system installation
        #  become: yes
        #  flatpak_remote:
        #    name: flathub
        #    state: present
        #    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        #
        #- name: Install Signal messenger
        #  become: yes
        #  flatpak:
        #    name: org.signal.Signal
        #    state: present
        #    remote: flathub


- name: Install packages via pip
  become: yes
  pip:
    name: 
      - wheel
      - pyserial
      - numpy 

- name: Enable systemd services
  become: yes
  systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  loop:
  - libvirtd
  - sshd
  
  
