- name: Fedora rpm fusion
  become: yes
  shell: "dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

- name: Install dnf packages
  become: yes
  dnf:
    state: latest
    name: 
      - '@Development Tools'
      - '@Development Libraries'
      - make
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
      - python3-pip
      - dnf-plugins-core
      - gnome-tweaks
      - mosh
      - tmux
      - mpv
      - vim
      - neovim
      - nmap
      - appeditor
      - nextcloud-client
      - gstreamer1-devel
      - gstreamer1-plugins-base-tools
      - gstreamer1-doc
      - gstreamer1-plugins-base-devel 
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-devel
      - gstreamer1-plugins-bad-free-extras
      - qbittorrent
      - tilix
      - htop
      - foliate
      - bridge-utils
      - libvirt
      - virt-install
      - qemu-kvm
      - libvirt-devel
      - virt-top
      - libguestfs-tools
      - virt-manager
      - openssh-server
      - ansible
      - yubikey-manager
      - nodejs
      - autofs
      - acpid
      - dkms
      - ncurses-compat-libs
      - alacritty
      - yt-dlp
      - ffmpeg
      - inxi
      - nemo
      - nemo-extensions
      - nemo-fileroller
      - kleopatra
      - neofetch



- name: Install packages via pip
  become: yes
  pip:
    name: 
      - wheel
      - pyserial
      - numpy 

- name: Enable systemd services
  become: yes
  systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  loop:
  - libvirtd
  - sshd
  
  
- name: Disable systemd services
  become: yes
  systemd:
    state: stopped 
    enabled: no 
    name: "{{ item }}"
  loop:
  - abrt-journal-core
  - abrt-oops
  - abrt-xorg
  - abrtd
